kind: Service
apiVersion: v1
metadata:
  name: firmament-service
  namespace: kube-system
spec:
  selector:
    scheduler: firmament
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firmament-scheduler
  namespace: kube-system
  labels:
    scheduler: firmament
spec:
  replicas: 1
  template:
    metadata:
      labels:
        scheduler: firmament
    spec:
      containers:
      - command: [/firmament/build/src/firmament_scheduler, --flagfile=/firmament/config/firmament_scheduler.cfg_cpu_cost, --firmament_scheduler_service_address=0.0.0.0, --flow_scheduling_binary=/firmament/build/third_party/cs2/src/cs2/cs2.exe]
        image: shivramsrivastava/firmament:dev
        name: firmament-scheduler
        ports:
         - containerPort: 9090
      hostNetwork: true
      hostPID: false
      volumes: []
