kind: Service
apiVersion: v1
metadata:
  name: firmament-service
  namespace: kube-system
spec:
  selector:
    scheduler: firmament
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: firmament-scheduler
  namespace: kube-system
  labels:
    scheduler: firmament
spec:
  replicas: 1
  template:
    metadata:
      labels:
        scheduler: firmament
    spec:
      containers:
      - command: [/firmament/build/src/firmament_scheduler, --flagfile=/firmament/config/firmament_scheduler_cpu_mem.cfg]
        image: huaweifirmament/firmament:latest
        name: firmament-scheduler
        ports:
         - containerPort: 9090
      hostNetwork: true
      hostPID: false
      volumes: []
