apiVersion: v1
kind: ServiceAccount
metadata:
  name: poseidon
  namespace: kube-system
---
kind: Service
apiVersion: v1
metadata:
  name: poseidon
  namespace: kube-system
spec:
  selector:
    poseidonservice: poseidon
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    component: poseidon
    tier: control-plane
    poseidonservice: poseidon
  name: poseidon
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: poseidon
        tier: control-plane
        version: first
        poseidonservice: poseidon
    spec:
      serviceAccountName: poseidon
      containers:
      - command: [/poseidon, --logtostderr, --kubeConfig=, --kubeVersion=1.6]
        image: gcr.io/poseidon-173606/poseidon:latest
        name: poseidon
      initContainers:
      - name: init-firmamentservice
        image: radial/busyboxplus:curl
        command: ['sh', '-c', 'until nslookup firmament-service.kube-system; do echo waiting for firmamentservice; sleep 1; done;']
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
